#!/usr/bin/env bash

WORKING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf $WORKING_DIR/build/classes/*
rm -rf $WORKING_DIR/build/incremental/*
rm -rf $WORKING_DIR/build/output/*
rm -rf $WORKING_DIR/build/sources/*
rm -rf $WORKING_DIR/build/stubs/*
